---
name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    strategy:
      matrix:
        node-version: [14.x]
    name: Node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ matrix.node-version }}
        uses: actions/checkout@v3

      - name: Setup and Test ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}

      - name: Install node modules
        shell: bash
        run: npm i

      - name: Unit testing
        shell: bash
        run: npm run test:unit

      - name: Integration testing
        shell: bash
        run: npm run test:integration
